version: "3"

services:
  database:
    image: postgres
    ports:
      - 5003:5432
    # volumes:
    #   - /custom/mount:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
volumes:
  pgdata:
